name: Streamlit Deploy
description: Deploy streamlit to Cloud Run
inputs:
  terraform-version:
    description: The version of Terraform to use
    default: 1.8.5
  terraform_directory:
    description: The directory containing the Terraform configuration
    default: terraform
  region:
    description: GCP Region to deploy to
    default: europe-west1
  project:
    description: GCP Project to deploy to
    required: true

outputs:
  cloud_run_url:
    description: The URL of the deployed Cloud Run streamlit app
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: composite

  steps:
    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Download Terraform State Artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: terraform.tfstate
        path: ${{ inputs.terraform_directory }}

    - name: Terraform Run
      id: terraform-run
      shell: bash
      run: |
        terraform init
        terraform validate
        terraform plan -out=tf.plan --var region=${{ inputs.region }} --var project_id=${{ inputs.project }}
        terraform apply tf.plan
      working-directory: ${{ inputs.terraform_directory }}

    - name: Upload Terraform State Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform.tfstate
        path: ${{ inputs.terraform_directory }}/terraform.tfstate
        retention-days: 90
        github-token: ${{ inputs.github_token }}
